name: Tests Unitaires

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Configuration de l'environnement Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Installation des dépendances
      run: |
        pip install pytest

    - name: Exécution des tests
      run: pytest
    
